repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.3.1
  hooks:
    - id: check-github-workflows
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      # because pre-commit invokes flake8 directly on files, the exclude in
      # `.flake8` config does not apply and the files must be excluded from the hook
      exclude: ^migrations/.*
      additional_dependencies: ['flake8-bugbear==21.4.3']
