matrix:
      include:
        - python: 3.7
          dist: xenial
          sudo: true

services:
      - redis-server

before_install:
      - sudo apt-get update -q


install:
      - cd forwarder
      - pip install .

script:
      - pwd
      - flake8 forwarder
