language: python
python:
      - "3.6"

services:
      - redis-server

before_install:
      - sudo apt-get update -q

install:
      - cd forwarder
      - python$PY -m pip install .

script:
      - pip install -r test-requirements.txt
      - #flake8 forwarder
      - python$PY -c "import forwarder"
