version: '2'
services:
  funcx-web-service:
    build: .
    ports:
      - "8080:8080"
    env_file: funcx-web-service.env
    volumes:
      - .:/opt/funcx-web-service
  forwarder:
    build: forwarder
    ports:
      - "8081:8080"
    volumes:
      - ./forwarder:/opt/forwarder
  serializer:
    build: serializer
    ports:
      - "8082:8080"
    volumes:
      - ./serializer:/opt/serializer
  mockrds:
    build: dockers/rds
    ports:
      - "5432:5432"
  mockredis:
    build: dockers/redis
    ports:
      - "6379:6379"