version: '3.8'
services:
  funcx-web-service:
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      - FLASK_APP=funcx-web-service
      - FLASK_DEBUG=1
    env_file: funcx-web-service.env
    volumes: [".:/opt/funcx-web-service"]
    secrets:
      - globus_client
      - globus_key
      - web_cert
      - web_key
    networks:
      default:
        aliases:
          - funcx.org
    cap_add:
      - NET_ADMIN
      - NET_RAW
  forwarder:
    build: forwarder
    ports:
      - "8081:8080"
    volumes:
      - ./forwarder:/opt/forwarder
    depends_on:
      - funcx-web-service
      - mockredis
  serializer:
    build: serializer
    ports:
      - "8082:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serializer/serializer:/opt/serializer
  mockrds:
    build: dockers/rds
    ports:
      - "5432:5432"
  mockredis:
    build: dockers/redis
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
  endpoints:
    build: dockers/endpoints
    ports:
      - "8888:8888"
    volumes:
      - ./dockers/endpoints:/data
    secrets:
      - web_cert
      - funcx_sdk_tokens
      - funcx_config
    depends_on:
      - funcx-web-service
      - forwarder
secrets:
  globus_client:
    file: dockers/secrets/globus_client.txt
  globus_key:
    file: dockers/secrets/globus_key.txt
  web_cert:
    file: dockers/secrets/web-cert.pem
  web_key:
    file: dockers/secrets/web-key.pem
  funcx_sdk_tokens:
    file: dockers/secrets/funcx-credentials/funcx_sdk_tokens.json
  funcx_config:
    file: dockers/secrets/funcx-config.py
