name: CI/CD

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: python -m pip install tox
    - name: Lint
      run: python -m tox -e lint,mypy
    - name: Safety Check
      run: python -m tox -e safety
    - name: Test
      run: python -m tox -e py
    - name: Report coverage with Codecov
      run: python -m tox -e codecov -- --token=${{ secrets.CODECOV_TOKEN }}

  publish:
    # only trigger on pushes to the main repo (not forks, and not PRs)
    if: ${{ github.repository == 'funcx-faas/funcx-web-service' && github.event_name == 'push' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
      id: extract_tag_name

    - name: Build funcX-web-service Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: funcx/web-service:${{ steps.extract_tag_name.outputs.imagetag }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"

#  If this is a merge to main branch then we want to restart the web service
#  pod on dev cluster to pick up the changes
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: scale to webservice pods to zero
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
        with:
          args:  scale deployment funcx-funcx-web-service --replicas=0

      - name: scale to webservice pods back up
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
        with:
          args:  scale deployment funcx-funcx-web-service --replicas=1
